### PR TITLE
Ru lang

### PR DESCRIPTION
**Pull request by Alkmaaar**
Maybe let's try it step by step old method? So i can see on genshinmap already translated 3 positions - Apple Berry Egg, so we can continue this way or? you can try realized your idea about translating, i will wait and after that start localization. What you think about it?

### CODE REVIEW

**Comment by EliteMasterEric** [comment]
You have to edit the `develop` branch for me to be able to merge it.

**Comment by Alkmaaar** [comment]
> You have to edit the `develop` branch for me to be able to merge it.

Do i understand right, i have to edit develop branch in my repository and pull commits exactly from develop branch?

**Comment by EliteMasterEric** [comment]
> 
> 
> > You have to edit the `develop` branch for me to be able to merge it.
> 
> Do i understand right, i have to edit develop branch in my repository and pull commits exactly from develop branch?

Yeah, that helps at least.

Currently the problem is with the fact that v0.10 is a separate branch right now with all the changes I'm making, and that's causing Git to modify a lot more files since your changes are based on the stable `master` branch.

If you are using the web brower (going to each file and clicking Edit), all you have to do is use the dropdown at the top left.

If you've downloaded the repository with Git, you'll have to perform a checkout to select the "develop" branch.

For the future, I'm trying to figure out a scheme for editing the feature names and popup descriptions in a way that makes sense.

**Comment by EliteMasterEric** [comment]
Now that v0.10 is stable (sorry for the wait) I'm merging these changes now and resolving any conflicts. I've added the translations and they should appear in v0.10.7.

**Pull request closed without merging**
